### ISSUE TITLE
Reordering columns does not trigger change detection because jQuery sortable callback

### ISSUE THREAD

**Issue by kevinmerckx** [zorec/ng2-pack#1]
Culprit in `thead.component`. I think a call to `.detectChanges()` is not enough because it will only run in the component and children [angular doc](https://angular.io/docs/ts/latest/api/core/index/ChangeDetectorRef-class.html). You should run some code into a "zone". [thougtram](http://blog.thoughtram.io/angular/2016/02/01/zones-in-angular-2.html) 

```
private initializeSortable() {
    jQuery(this.elementRef.nativeElement).sortable({
      cursor: 'move',
      axis: 'x',
      tolerance: 'pointer',
      items: '.drag-column',
      handle: '.col-label',
      update: () => {
        this.draggedColumnId = '';
        let sortedIDs = jQuery( this.elementRef.nativeElement )
          .sortable( 'toArray', {
            attribute: 'data-col-ref'
          });
        this.visibleColumns = sortedIDs;
        this.reorderColumns.emit(sortedIDs);
       >>>>>>>>>>>>>>> this.changeDetectorRef.detectChanges(); <<<<<<<<<<<<<<<<<<<<<<<<
      },
      // NOTE: provide additional information about dragging
      // when dragging is started
      // activate: (event: any, ui: any) => {
      //   this.draggedColumnId = ui.item.attr('data-col-ref');
      // },
      // stop: () => {
      //   this.draggedColumnId = '';
      //   this.changeDetectorRef.detectChanges();
      // }
    });
    jQuery(this.elementRef.nativeElement).disableSelection();
  }
```

**Comment by zorec** [comment]
This has been fixed in version 0.4.1. 
As mentioned in README, jQuery UI Sortable was an only temporary solution. Now it is replaced by our [sortable module](https://github.com/zorec/ng2-pack/tree/refactor/state-management/src/lib/sortable) for the sake of reducing dependencies and adding new features (e.g. preview rows content when reordering columns). 
You can test it in the demo app https://zorec.github.io/ng2-pack/.
